// Package skills implements the Skills component.
//
// It embeds core skills into the binary at compile time and provides
// logic to render, inject, and manage skills for any agent config.
//
// Skill categories:
//   - Core: embedded generic skills (architecture, testing, git-workflow)
//   - Stack: downloaded from a registry (placeholder — future)
//   - Project: generated by eva init based on codebase scan
//   - User: added manually via URL or local path
package skills

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// — Embed core skills at compile time —

//go:embed core/architecture/SKILL.md
var architectureSkill string

//go:embed core/testing/SKILL.md
var testingSkill string

//go:embed core/git-workflow/SKILL.md
var gitWorkflowSkill string

//go:embed templates/SKILL-template.md
var skillTemplate string

// CoreSkill represents a skill embedded in the binary.
type CoreSkill struct {
	Name        string // e.g. "architecture"
	Description string // one line
	Trigger     string // keywords that activate this skill
	Content     string // full SKILL.md content
}

// CoreSkills returns all embedded core skills.
func CoreSkills() []CoreSkill {
	return []CoreSkill{
		{
			Name:        "architecture",
			Description: "Stack decisions, project structure, patterns, state management, and technical conventions.",
			Trigger:     "stack, patterns, architecture, structure, state, conventions, module, dependency",
			Content:     architectureSkill,
		},
		{
			Name:        "testing",
			Description: "Testing conventions, patterns, coverage expectations, and tooling.",
			Trigger:     "test, testing, coverage, unit test, integration test, e2e, mock, fixture",
			Content:     testingSkill,
		},
		{
			Name:        "git-workflow",
			Description: "Git conventions — branching, commits, PRs, and release workflow.",
			Trigger:     "git, commit, branch, PR, pull request, merge, release, changelog, conventional commits",
			Content:     gitWorkflowSkill,
		},
	}
}

// Component implements the Skills injectable component.
type Component struct{}

// New constructs a new Skills Component.
func New() *Component {
	return &Component{}
}

// Name returns the component identifier.
func (c *Component) Name() string {
	return "skills"
}

// Template returns the SKILL template for generating project-specific skills.
// Used by eva init when scanning the codebase.
func (c *Component) Template() string {
	return skillTemplate
}

// Render builds the skills block to inject into an agent config file.
// This is a lightweight pointer — the actual SKILL.md files live in .eva/skills/.
// The agent reads .eva/skills/README.md to discover available skills.
func (c *Component) Render() string {
	var b strings.Builder

	b.WriteString("## Skills\n\n")
	b.WriteString("Skills are loaded from `.eva/skills/` on demand.\n")
	b.WriteString("Read `.eva/skills/README.md` to see available skills and their triggers.\n")
	b.WriteString("Load only the skills relevant to your current task.\n\n")
	b.WriteString("### Available core skills\n\n")

	for _, skill := range CoreSkills() {
		b.WriteString(fmt.Sprintf("- **%s** — %s\n", skill.Name, skill.Description))
	}

	b.WriteString("\n### Adding skills\n\n")
	b.WriteString("- Project skills: generated by `eva init`\n")
	b.WriteString("- User skills: `eva skill add <path-or-url>`\n")
	b.WriteString("- Stack skills: `eva skills install <stack-name>`\n")

	return b.String()
}

// InjectIntoFile appends the skills block to an existing config file.
// If the file already contains skills content (detected by the header),
// it replaces the existing block instead of duplicating it.
func (c *Component) InjectIntoFile(path string) error {
	existing, err := readFileOrEmpty(path)
	if err != nil {
		return fmt.Errorf("skills: failed to read %s: %w", path, err)
	}

	rendered := c.Render()

	var updated string
	if containsSkills(existing) {
		updated = replaceSkills(existing, rendered)
	} else {
		updated = appendSkills(existing, rendered)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("skills: failed to create directory for %s: %w", path, err)
	}

	if err := os.WriteFile(path, []byte(updated), 0644); err != nil {
		return fmt.Errorf("skills: failed to write %s: %w", path, err)
	}

	return nil
}

// InitSkillsDir creates the .eva/skills/ directory and writes core skills.
// Called by eva init — sets up the skill files that agents will read.
//
// Structure created:
//
//	projectDir/.eva/skills/
//	├── README.md                  ← skill index with triggers
//	├── architecture/SKILL.md      ← core skill
//	├── testing/SKILL.md           ← core skill
//	└── git-workflow/SKILL.md      ← core skill
func (c *Component) InitSkillsDir(projectDir string) error {
	skillsDir := filepath.Join(projectDir, ".eva", "skills")

	// Write each core skill
	for _, skill := range CoreSkills() {
		skillDir := filepath.Join(skillsDir, skill.Name)
		if err := os.MkdirAll(skillDir, 0755); err != nil {
			return fmt.Errorf("skills: failed to create %s: %w", skillDir, err)
		}

		skillPath := filepath.Join(skillDir, "SKILL.md")
		if err := writeIfNotExists(skillPath, skill.Content); err != nil {
			return fmt.Errorf("skills: failed to write %s: %w", skillPath, err)
		}
	}

	// Write the README index
	readmePath := filepath.Join(skillsDir, "README.md")
	readme := renderSkillsREADME(CoreSkills())
	if err := writeIfNotExists(readmePath, readme); err != nil {
		return fmt.Errorf("skills: failed to write README.md: %w", err)
	}

	return nil
}

// InitProjectSkillsDir creates empty directories for project-specific skills.
// These will be populated by eva init's codebase scan.
func (c *Component) InitProjectSkillsDir(projectDir string) error {
	dirs := []string{
		filepath.Join(projectDir, ".eva", "shared-skills"),
		filepath.Join(projectDir, ".eva", "docs"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("skills: failed to create %s: %w", dir, err)
		}
	}
	return nil
}

// AddFromPath copies a SKILL.md from a local path into .eva/skills/.
func (c *Component) AddFromPath(projectDir, sourcePath string) error {
	content, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("skills: failed to read %s: %w", sourcePath, err)
	}

	skillName := extractSkillName(string(content))
	if skillName == "" {
		skillName = filepath.Base(filepath.Dir(sourcePath))
	}

	skillDir := filepath.Join(projectDir, ".eva", "skills", skillName)
	if err := os.MkdirAll(skillDir, 0755); err != nil {
		return fmt.Errorf("skills: failed to create %s: %w", skillDir, err)
	}

	destPath := filepath.Join(skillDir, "SKILL.md")
	if err := os.WriteFile(destPath, content, 0644); err != nil {
		return fmt.Errorf("skills: failed to write %s: %w", destPath, err)
	}

	return nil
}

// — internal helpers —

const skillsMarkerStart = "<!-- eva:skills:start -->"
const skillsMarkerEnd = "<!-- eva:skills:end -->"

func containsSkills(content string) bool {
	return strings.Contains(content, skillsMarkerStart)
}

func appendSkills(existing, rendered string) string {
	separator := "\n\n"
	if existing == "" {
		separator = ""
	}
	return existing + separator +
		skillsMarkerStart + "\n" +
		rendered +
		skillsMarkerEnd + "\n"
}

func replaceSkills(existing, rendered string) string {
	start := strings.Index(existing, skillsMarkerStart)
	end := strings.Index(existing, skillsMarkerEnd)

	if start == -1 || end == -1 {
		return appendSkills(existing, rendered)
	}

	before := existing[:start]
	after := existing[end+len(skillsMarkerEnd):]

	return before +
		skillsMarkerStart + "\n" +
		rendered +
		skillsMarkerEnd + "\n" +
		after
}

func readFileOrEmpty(path string) (string, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	return string(content), nil
}

func writeIfNotExists(path, content string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return os.WriteFile(path, []byte(content), 0644)
}

// renderSkillsREADME generates the .eva/skills/README.md index.
func renderSkillsREADME(skills []CoreSkill) string {
	var b strings.Builder

	b.WriteString("# Project Skills\n\n")
	b.WriteString("Skills are loaded on demand by SDD agents.\n")
	b.WriteString("Each skill defines when it should be loaded via its `trigger` field.\n\n")
	b.WriteString("## Available Skills\n\n")
	b.WriteString("| Skill | Trigger |\n")
	b.WriteString("|---|---|\n")

	for _, s := range skills {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n", s.Name, s.Trigger))
	}

	b.WriteString("\n### Adding a skill\n\n")
	b.WriteString("```bash\n")
	b.WriteString("# From a local file\n")
	b.WriteString("eva skill add ./path/to/SKILL.md\n\n")
	b.WriteString("# From a URL\n")
	b.WriteString("eva skill add https://raw.githubusercontent.com/.../SKILL.md\n")
	b.WriteString("```\n")

	return b.String()
}

// extractSkillName parses the `name` field from a SKILL.md frontmatter.
func extractSkillName(content string) string {
	const prefix = "name:"
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
		}
	}
	return ""
}
